version: '3'

services:
  front-end-service:
    build: 
      context: ../front-end
      dockerfile: ../front-end/front-end-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
